BerlingskeMedia/bpc_console

.github/pull_request_template.md, server/index.js
https://berlingskemedia.atlassian.net/browse/BMD-3790
(none)
=> BMD-3790 X-Frame-Options added

client/src/users.js
https://berlingskemedia.atlassian.net/browse/{id}
(none)
=> BMD-3495 only log in console to mute error

server/index.js
https://berlingskemedia.atlassian.net/browse/BMD-3790
(none)
=> BMD-3790 boom in response managed

client/src/company.js, client/src/payments.js, package-lock.json, package.json
https://berlingskemedia.atlassian.net/browse/BMD-4297
(none)
=> BMD-4297 add email mask on company level

.env.dev, Dockerfile, Dockerfile.dev, README.md, client/src/applicationGrants.js, client/src/components/bpc.js, client/src/components/bpp.js, client/src/components/pm.js, docker-compose.dev.yaml, package-lock.json, package.json, webpack.config.js
https://berlingskemedia.atlassian.net/browse/BMD-6307
(none)
=> BMD-6307: better environmants support and new work with new HAPI

Dockerfile, package-lock.json
https://berlingskemedia.atlassian.net/browse/BMD-6307
(none)
=> Bmd 6307 fix npx

client/src/components/bpp.js, client/src/components/pm.js
https://berlingskemedia.atlassian.net/browse/BMD-6804
(none)
=> BMD-6804 add content type for relative apis

client/index.html, server/index.js, webpack.config.js
https://berlingskemedia.atlassian.net/browse/BMD-6476
(none)
=> BMD-6476 hawk processed by webpack and served as normal js file

client/index.html, client/src/components/bpc.js, client/src/components/bpp.js, client/src/components/pm.js, client/src/tools.js, webpack.config.js
https://berlingskemedia.atlassian.net/browse/BMD-6992
(none)
=> BMD-6992 missing Hawk

client/src/payment.js
https://berlingskemedia.atlassian.net/browse/BMD-6410
(none)
=> BMD-6410: uncovered aditional fields for payment list

package-lock.json, package.json
https://berlingskemedia.atlassian.net/browse/BMD-7505
(none)
=> BMD-7505: fix production builds

.drone.yml
https://berlingskemedia.atlassian.net/browse/BMD-7505
(none)
=> aws urls for pre-production

client/src/company.js, client/src/components/arrayItems.js
https://berlingskemedia.atlassian.net/browse/BMD-8795
(none)
=> BMD-8795 ArrayItems as checkboxes

client/src/company.js
https://berlingskemedia.atlassian.net/browse/BMD-8789
(none)
=> BMD-8789 check if users exists in grants

client/src/company.js, client/src/companyUsers.js, package-lock.json, package.json, webpack.config.js
https://berlingskemedia.atlassian.net/browse/BMD-8789
(none)
=> BMD-8789 fix

package-lock.json, package.json
https://berlingskemedia.atlassian.net/browse/BMD-8789
(none)
=> BMD-8789 @babel/plugin-transform-runtime as normap dep

client/src/users.js
https://berlingskemedia.atlassian.net/browse/BMD-9086
(none)
=> BMD-9086 Fix reset password

client/src/companyPlaninstances.js
https://berlingskemedia.atlassian.net/browse/BMD-8125
(none)
=> BMD-8125 Units counter update

client/src/applicationGrants.js
https://berlingskemedia.atlassian.net/browse/BMD-9551
(none)
=> BMD-9551 fixed adding grants

client/src/company.js, server/geo_lookup.js
https://berlingskemedia.atlassian.net/browse/BMD-9605
(none)
=> BMD-9605 missing city in geo fix

client/src/applicationGrants.js
https://berlingskemedia.atlassian.net/browse/BMD-9827
(none)
=> BMD-9827 added missing user in GrantsTable
